var streetsStyle = {
	"11": {
		"motorway": { "color": "#FF0000", "weight": 3.6, "opacity": 1, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"mainroad": { "color": "#FF0000", "weight": 2, "opacity": 1, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"minorroad": { "color": "#FF0000", "weight": 0.4, "opacity": 1, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram1": { "color": "#004586", "weight": 2, "opacity": 0.9, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram2": { "color": "#ff420e", "weight": 2, "opacity": 0.9, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram3": { "color": "#ffd320", "weight": 2, "opacity": 0.9, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram4": { "color": "#579d1c", "weight": 2, "opacity": 0.9, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram5": { "color": "#7e0021", "weight": 2, "opacity": 0.9, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram6": { "color": "#83caff", "weight": 2, "opacity": 0.9, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram7": { "color": "#314004", "weight": 2, "opacity": 0.9, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram8": { "color": "#aecf00", "weight": 2, "opacity": 0.9, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram9": { "color": "#4b1f6f", "weight": 2, "opacity": 0.9, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram10": { "color": "#ff950e", "weight": 2, "opacity": 0.9, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram11": { "color": "#c5000b", "weight": 2, "opacity": 0.9, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram12": { "color": "#0084d1", "weight": 2, "opacity": 0.9, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"unknown": { "color": "#ffff99", "weight": 2, "opacity": 0.9, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"service": { "color": "#FF0000", "weight": 0.3, "opacity": 1, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"noauto": { "color": "#FF0000", "weight": 0.3, "opacity": 1, "fill": false, "lineCap": "butt", "lineJoin": "round" }
	},
	"12": {
		"motorway": { "color": "#FF0000", "weight": 4.5, "opacity": 1, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"mainroad": { "color": "#FF0000", "weight": 2.2, "opacity": 1, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"minorroad": { "color": "#FF0000", "weight": 0.8, "opacity": 1, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram1": { "color": "#004586", "weight": 3, "opacity": 0.8, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram2": { "color": "#ff420e", "weight": 3, "opacity": 0.8, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram3": { "color": "#ffd320", "weight": 3, "opacity": 0.8, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram4": { "color": "#579d1c", "weight": 3, "opacity": 0.8, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram5": { "color": "#7e0021", "weight": 3, "opacity": 0.8, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram6": { "color": "#83caff", "weight": 3, "opacity": 0.8, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram7": { "color": "#314004", "weight": 3, "opacity": 0.8, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram8": { "color": "#aecf00", "weight": 3, "opacity": 0.8, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram9": { "color": "#4b1f6f", "weight": 3, "opacity": 0.8, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram10": { "color": "#ff950e", "weight": 3, "opacity": 0.8, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram11": { "color": "#c5000b", "weight": 3, "opacity": 0.8, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram12": { "color": "#0084d1", "weight": 3, "opacity": 0.8, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"unknown": { "color": "#ffff99", "weight": 3, "opacity": 0.8, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"service": { "color": "#FF0000", "weight": 0.5, "opacity": 1, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"noauto": { "color": "#FF0000", "weight": 0.5, "opacity": 1, "fill": false, "lineCap": "butt", "lineJoin": "round" }
	},
	"13": {
		"motorway": { "color": "#FF0000", "weight": 5, "opacity": 1, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"mainroad": { "color": "#FF0000", "weight": 3.5, "opacity": 1, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"minorroad": { "color": "#FF0000", "weight": 3, "opacity": 1, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram1": { "color": "#004586", "weight": 4, "opacity": 0.7, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram2": { "color": "#ff420e", "weight": 4, "opacity": 0.7, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram3": { "color": "#ffd320", "weight": 4, "opacity": 0.7, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram4": { "color": "#579d1c", "weight": 4, "opacity": 0.7, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram5": { "color": "#7e0021", "weight": 4, "opacity": 0.7, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram6": { "color": "#83caff", "weight": 4, "opacity": 0.7, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram7": { "color": "#314004", "weight": 4, "opacity": 0.7, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram8": { "color": "#aecf00", "weight": 4, "opacity": 0.7, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram9": { "color": "#4b1f6f", "weight": 4, "opacity": 0.7, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram10": { "color": "#ff950e", "weight": 4, "opacity": 0.7, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram11": { "color": "#c5000b", "weight": 4, "opacity": 0.7, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram12": { "color": "#0084d1", "weight": 4, "opacity": 0.7, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"unknown": { "color": "#ffff99", "weight": 4, "opacity": 0.7, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"service": { "color": "#FF0000", "weight": 1, "opacity": 1, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"noauto": { "color": "#FF0000", "weight": 1, "opacity": 1, "fill": false, "lineCap": "butt", "lineJoin": "round" }
	},
	"14": { 
		"motorway": { "color": "#FF0000", "weight": 6, "opacity": 0.3, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"mainroad": { "color": "#FF0000", "weight": 4.5, "opacity": 0.3, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"minorroad": { "color": "#FF0000", "weight": 3.6, "opacity": 0.3, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram1": { "color": "#004586", "weight": 5, "opacity": 0.6, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram2": { "color": "#ff420e", "weight": 5, "opacity": 0.6, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram3": { "color": "#ffd320", "weight": 5, "opacity": 0.6, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram4": { "color": "#579d1c", "weight": 5, "opacity": 0.6, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram5": { "color": "#7e0021", "weight": 5, "opacity": 0.6, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram6": { "color": "#83caff", "weight": 5, "opacity": 0.6, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram7": { "color": "#314004", "weight": 5, "opacity": 0.6, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram8": { "color": "#aecf00", "weight": 5, "opacity": 0.6, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram9": { "color": "#4b1f6f", "weight": 5, "opacity": 0.6, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram10": { "color": "#ff950e", "weight": 5, "opacity": 0.6, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram11": { "color": "#c5000b", "weight": 5, "opacity": 0.6, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram12": { "color": "#0084d1", "weight": 5, "opacity": 0.6, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"unknown": { "color": "#ffff99", "weight": 5, "opacity": 0.6, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"service": { "color": "#FF0000", "weight": 1, "opacity": 0.3, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"noauto": { "color": "#FF0000", "weight": 1, "opacity": 0.3, "fill": false, "lineCap": "butt", "lineJoin": "round" }
	},
	"15": {
		"motorway": { "color": "#FF0000", "weight": 8.5, "opacity": 0.3, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"mainroad": { "color": "#FF0000", "weight": 6, "opacity": 0.3, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"minorroad": { "color": "#FF0000", "weight": 4, "opacity": 0.3, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram1": { "color": "#004586", "weight": 6, "opacity": 0.5, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram2": { "color": "#ff420e", "weight": 6, "opacity": 0.5, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram3": { "color": "#ffd320", "weight": 6, "opacity": 0.5, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram4": { "color": "#579d1c", "weight": 6, "opacity": 0.5, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram5": { "color": "#7e0021", "weight": 6, "opacity": 0.5, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram6": { "color": "#83caff", "weight": 6, "opacity": 0.5, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram7": { "color": "#314004", "weight": 6, "opacity": 0.5, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram8": { "color": "#aecf00", "weight": 6, "opacity": 0.5, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram9": { "color": "#4b1f6f", "weight": 6, "opacity": 0.5, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram10": { "color": "#ff950e", "weight": 6, "opacity": 0.5, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram11": { "color": "#c5000b", "weight": 6, "opacity": 0.5, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram12": { "color": "#0084d1", "weight": 6, "opacity": 0.5, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"unknown": { "color": "#ffff99", "weight": 6, "opacity": 0.5, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"service": { "color": "#FF0000", "weight": 2.66, "opacity": 0.3, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"noauto": { "color": "#FF0000", "weight": 2.5, "opacity": 0.3, "fill": false, "lineCap": "butt", "lineJoin": "round" }
	},
	"16": {
		"motorway": { "color": "#FF0000", "weight": 10.5, "opacity": 0.3, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"mainroad": { "color": "#FF0000", "weight": 8.5, "opacity": 0.3, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"minorroad": { "color": "#FF0000", "weight": 6, "opacity": 0.3, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram1": { "color": "#004586", "weight": 7, "opacity": 0.4, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram2": { "color": "#ff420e", "weight": 7, "opacity": 0.4, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram3": { "color": "#ffd320", "weight": 7, "opacity": 0.4, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram4": { "color": "#579d1c", "weight": 7, "opacity": 0.4, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram5": { "color": "#7e0021", "weight": 7, "opacity": 0.4, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram6": { "color": "#83caff", "weight": 7, "opacity": 0.4, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram7": { "color": "#314004", "weight": 7, "opacity": 0.4, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram8": { "color": "#aecf00", "weight": 7, "opacity": 0.4, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram9": { "color": "#4b1f6f", "weight": 7, "opacity": 0.4, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram10": { "color": "#ff950e", "weight": 7, "opacity": 0.4, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram11": { "color": "#c5000b", "weight": 7, "opacity": 0.4, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram12": { "color": "#0084d1", "weight": 7, "opacity": 0.4, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"unknown": { "color": "#ffff99", "weight": 7, "opacity": 0.4, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"service": { "color": "#FF0000", "weight": 3.3, "opacity": 0.3, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"noauto": { "color": "#FF0000", "weight": 3, "opacity": 0.3, "fill": false, "lineCap": "butt", "lineJoin": "round" }
	},
	"17": {
		"motorway": { "color": "#FF0000", "weight": 17, "opacity": 0.3, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"mainroad": { "color": "#FF0000", "weight": 14.5, "opacity": 0.3, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"minorroad": { "color": "#FF0000", "weight": 12, "opacity": 0.3, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram1": { "color": "#004586", "weight": 15, "opacity": 0.3, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram2": { "color": "#ff420e", "weight": 15, "opacity": 0.3, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram3": { "color": "#ffd320", "weight": 15, "opacity": 0.3, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram4": { "color": "#579d1c", "weight": 15, "opacity": 0.3, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram5": { "color": "#7e0021", "weight": 15, "opacity": 0.3, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram6": { "color": "#83caff", "weight": 15, "opacity": 0.3, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram7": { "color": "#314004", "weight": 15, "opacity": 0.3, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram8": { "color": "#aecf00", "weight": 15, "opacity": 0.3, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram9": { "color": "#4b1f6f", "weight": 15, "opacity": 0.3, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram10": { "color": "#ff950e", "weight": 15, "opacity": 0.3, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram11": { "color": "#c5000b", "weight": 15, "opacity": 0.3, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram12": { "color": "#0084d1", "weight": 15, "opacity": 0.3, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"unknown": { "color": "#ffff99", "weight": 15, "opacity": 0.3, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"service": { "color": "#FF0000", "weight": 5.3, "opacity": 0.3, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"noauto": { "color": "#FF0000", "weight": 8.5, "opacity": 0.3, "fill": false, "lineCap": "butt", "lineJoin": "round" }
	},
	"18": {
		"motorway": { "color": "#FF0000", "weight": 24, "opacity": 0.3, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"mainroad": { "color": "#FF0000", "weight": 21, "opacity": 0.3, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"minorroad": { "color": "#FF0000", "weight": 17.5, "opacity": 0.3, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram1": { "color": "#004586", "weight": 20, "opacity": 0.2, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram2": { "color": "#ff420e", "weight": 20, "opacity": 0.2, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram3": { "color": "#ffd320", "weight": 20, "opacity": 0.2, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram4": { "color": "#579d1c", "weight": 20, "opacity": 0.2, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram5": { "color": "#7e0021", "weight": 20, "opacity": 0.2, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram6": { "color": "#83caff", "weight": 20, "opacity": 0.2, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram7": { "color": "#314004", "weight": 20, "opacity": 0.2, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram8": { "color": "#aecf00", "weight": 20, "opacity": 0.2, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram9": { "color": "#4b1f6f", "weight": 20, "opacity": 0.2, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram10": { "color": "#ff950e", "weight": 20, "opacity": 0.2, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram11": { "color": "#c5000b", "weight": 20, "opacity": 0.2, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"diagram12": { "color": "#0084d1", "weight": 20, "opacity": 0.2, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"unknown": { "color": "#ffff99", "weight": 20, "opacity": 0.2, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"service": { "color": "#FF0000", "weight": 8.1, "opacity": 0.3, "fill": false, "lineCap": "butt", "lineJoin": "round" },
		"noauto": { "color": "#FF0000", "weight": 9.5, "opacity": 0.3, "fill": false, "lineCap": "butt", "lineJoin": "round" }
	}
};
